[project]
name = "veryl_keccak_f"
version = "0.1.1" 
repository = "https://github.com/ankoman/veryl_keccak_f"
categories = ["crypto"]
[build]
sources = ["src"]
target = {type = "directory", path = "target"}
[synth]
top          = "Keccak_f"
library      = "sky130"
clock_freq   = 500.0
activity     = 0.5
timing_paths = 1
[publish]
bump_commit = true
publish_commit = true
register = true